---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server-production
  namespace: argo
spec:
  destination:
    namespace: echo-server
    name: production
  project: default
  sources:
    - repoURL: https://public-helm-charts.naviteq.io/
      chart: http-echo-server
      targetRevision: "~> 0"
      helm:
        valueFiles:
        - $values/deployment/values/sandbox.yaml
        - $values/deployment/values/prod.yaml
    - repoURL: https://github.com/naviteq/http-echo-server
      ref: values
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
