---

name: CI (Main branch)
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@main
    with:
      REGISTRY: ghcr.io
      DOCKER_CONTEXT: app
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm:
    uses: naviteq/github-actions/.github/workflows/helm-release-github.yaml@main
    needs: [docker]
    with:
      chart_path: helm
      ghcr_repo: ${{ github.repository }}
      bump_version_in_git: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  release:
    uses: naviteq/github-actions/.github/workflows/create-release.yaml@main
    secrets: inherit
    needs:
      - docker
      - helm
